### PR TITLE
Tweaks to work with AuthLogic and namespaced classes

### PR DESCRIPTION
**Pull request by jocranford**
Authlogic uses regular expression validations containing \A and \z (e.g. for email and username validation) added replacement to ^ and $ so that it works on the client side. 

Using form_for with a class inside a module meant my input fields had names like module_class_name. The   logic to get the module name does not cope well with this, so I added an optional data attribute data-model-name to the input element. If this is present, it's used for uniqueness validations.

### CODE REVIEW

**Comment by dannyatFINE** [comment]
@joecorcoran Do you think this can be merged. We have 3 PR's open solving the `^` - `\A` and `$` - `\z` RegEx issue (#14, #34, and #36 respectively). Seems like the XRegExp plugin integration is a soon to be had feature.

Do you think one of these 3 PR's is stable enough to merge. At least until the plugin gets integrated into Judge?

**Comment by dannysperry** [comment]
@joecorcoran #14, #34, and #36 all solve the same problem. Do you think one of these PR's is stable enough to merge until the XRegExp plugin gets integrated?

**Comment by jamesmk** [comment]
@jocranford I was having issues with namspaced classes too and in March my PR was merged so Judge explicitly defines the class as `data-klass` (https://github.com/joecorcoran/judge/pull/52). This is now in v2.0.6 and I'm wondering if this fixes your need to override the class with `data-model-class`?

There's still the regex issue to solve, but can you update and let me know?

thanks!

**Comment by jamesmk** [comment]
I just merged a regex fix from https://github.com/joecorcoran/judge/pull/36. I hate to do this, since your PR was first, but the other fixes here are creating conflicts so I'm going to close this one.

**Pull request closed without merging**
