### PR TITLE
judge can use telephone_field form

### PR DESCRIPTION
**Pull request by MatsumotoHiroko**
I want to use telephone_field in form for.
please check my commit.

### CODE REVIEW

**Comment by joecorcoran** [comment]
Great, thanks for the PR! Happy to merge – however could you also add a spec for the field, e.g. https://github.com/MatsumotoHiroko/judge/blob/feature/use_telephone_field/spec/form_builder_spec.rb#L72-L74

**Comment by MatsumotoHiroko** [comment]
Thank you very  match. I will try to add code in spec. please waiting.
Sorry, my English isn't better.

**Comment by joecorcoran** [comment]
Excellent, thank you so much! :rocket:

**Comment by MatsumotoHiroko** [comment]
very thanks you!!!
my first gem commit.

**Comment by jamesmk** [comment]
@MatsumotoHiroko congrats!

**Pull request merged**
