### PR TITLE
fixes #33 - adds presence validation support for radio btns

### LINKED ISSUE #33: eachValidators.presence makes no sense for radio buttons
I worked around this with
```coffee
# fix the presence validator for radio buttons
judge.eachValidators.presence = (options, messages) ->
  if $(@).is(':radio')
    judge.closed(if $("[name=\"#{@.name}\"]:radio:checked").length then [] else [messages.blank])
  else
    judge.closed(if @value.length then [] else [messages.blank])
```
for now. It should probably be solved with a more generic `value = (elem) -> submitted_field_value` function and then checking `value(this)` instead of `this.value.length`.

### PR DESCRIPTION
**Pull request by jamesmk**
Inspired by @kirel's fix, this supports presence validation on radio buttons without a default.

@joecorcoran, @dannysperry, @saurabhbhatia let me know if you have any feedback, otherwise I'll merge it myself in a couple days.

thanks

### CODE REVIEW

**Comment by danieldocki** [comment]
My issue was fixed #57, good job :)

**Comment by saurabhbhatia** [comment]
Looks pretty good!

**Comment by danieldocki** [comment]
@jamesmk @saurabhbhatia 

I was testing here and when the radio have validation inclusion, is giving as valid, when receive different values.

Example:

```ruby
 validates :gender, inclusion: { in: %w(male female) }
```

```html
<div class="form-group radio_buttons required user_gender">
  <label class="radio_buttons required control-label">
    <abbr title="obrigatório">*</abbr> sexo
  </label>
  <span class="radio radio-inline radio__label">
    <input class="radio_buttons required form-control" data-validate="[{&quot;kind&quot;:&quot;presence&quot;,&quot;options&quot;:{},&quot;messages&quot;:{&quot;blank&quot;:&quot;não pode ficar em branco&quot;}},{&quot;kind&quot;:&quot;inclusion&quot;,&quot;options&quot;:{&quot;in&quot;:[&quot;male&quot;,&quot;female&quot;]},&quot;messages&quot;:{&quot;inclusion&quot;:&quot;não está incluído na lista&quot;,&quot;blank&quot;:&quot;não pode ficar em branco&quot;}}]" data-klass="User" type="radio" value="malex" name="user[gender]" id="user_gender_male" style="border: 1px solid rgb(239, 72, 54);">
    <label class="collection_radio_buttons" for="user_gender_male">papai</label>
  </span>
  <span class="radio radio-inline radio__label">
    <input class="radio_buttons required form-control" data-validate="[{&quot;kind&quot;:&quot;presence&quot;,&quot;options&quot;:{},&quot;messages&quot;:{&quot;blank&quot;:&quot;não pode ficar em branco&quot;}},{&quot;kind&quot;:&quot;inclusion&quot;,&quot;options&quot;:{&quot;in&quot;:[&quot;male&quot;,&quot;female&quot;]},&quot;messages&quot;:{&quot;inclusion&quot;:&quot;não está incluído na lista&quot;,&quot;blank&quot;:&quot;não pode ficar em branco&quot;}}]" data-klass="User" type="radio" value="female" name="user[gender]" id="user_gender_female" style="">
    <label class="collection_radio_buttons" for="user_gender_female">mamãe</label>
  </span>
</div>
```

**Comment by jamesmk** [comment]
@danieldocki Yeah, radio btn will have all sorts of weird edge cases like this. We'd have to add a radio specific conditional to each validator. That's not a priority though, because most of the use cases don't make sense. Inclusion, for example, can be defined by the radio btn values. Adding it as a validation seems redundant.

**Comment by danieldocki** [comment]
@jamesmk make sense

**Pull request merged**
